// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mumtoycbgdwfcxtuyiof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bXRveWNiZ2R3ZmN4dHV5aW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODA2NzMsImV4cCI6MjA2NTk1NjY3M30.9QxZbeiBLYoZ7t_MUB5iXCcu9UWOBA8ua0vmABfLsgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});